#
# Default values for dapr-store.
#

image:
  registry: ccr.ccs.tencentyun.com
  repo: v4ni11a
  tag: latest
  pullSecrets: []

auth:
  clientId:

mysql:
  connection:

ingress:
  host:
  certName:
  certIssuer:

resources:
  limits:
    cpu: 100m
    memory: 200M

cart:
  annotations:
  replicas: 1

orders:
  annotations:
  replicas: 1

products:
  annotations:
  replicas: 1

users:
  annotations:
  replicas: 1

frontendHost:
  annotations:
  replicas: 1

daprComponents:
  deploy: true
  state:
    name: statestore
    redisHost: redis-master.statestore.svc:6379
  pubsub:
    name: pubsub
    redisHost: redis-master.statestore.svc:6379
